version: "3"
services:
  discordbot:
    build: .
    restart: always
    build: .
    depends_on:
        - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo
    restart: unless-stopped
