version: "3"
services:
  discordbot:
    build: .
    restart: always
    image: xrisk/aocbot:stable
    depends_on:
        - mongodb
    restart_policy:
      condition: any
  mongodb:
    image: mongo
